decharges/decharge/urls.py
from django.urls import path

from decharges.decharge.views import (
    ApprocheDesReglesTelecharger,
    CreateQuotaETPFederation,
    CreateTempsDeDecharge,
    CreateUtilisationTempsDecharge,
    CTSCreate,
    CTSUpdate,
    ExportMinistere,
    FusionnerDoublons,
    HistoriquePage,
    HistoriqueTelecharger,
    IdentifierDoublons,
    ImportTempsSyndicats,
    PageAccueilSyndicatView,
    RenommerBeneficiaire,
    SuppressionTempsDeDecharge,
    SuppressionUtilisationTempsDecharge,
    SyndicatsARelancer,
    SyntheseCTS,
    UpdateQuotaETPFederation,
    UpdateTempsDeDecharge,
    UpdateUtilisationTempsDecharge,
)
from decharges.decharge.views.accueil import PageAccueilSyndicatChoisiView

app_name = "decharge"

urlpatterns = [
    path("", PageAccueilSyndicatView.as_view(), name="index"),
    path(
        "consulter-saisie/<int:pk>/",
        PageAccueilSyndicatChoisiView.as_view(),
        name="index-syndicat",
    ),
    path("import/", ImportTempsSyndicats.as_view(), name="import_temps"),
    path(
        "ajouter-beneficiaire/",
        CreateUtilisationTempsDecharge.as_view(),
        name="ajouter_beneficiaire",
    ),
    path(
        "modifier-beneficiaire/<int:pk>/",
        UpdateUtilisationTempsDecharge.as_view(),
        name="modifier_beneficiaire",
    ),
    path(
        "supprimer-beneficiaire/<int:pk>/",
        SuppressionUtilisationTempsDecharge.as_view(),
        name="supprimer_beneficiaire",
    ),
    path("export-ministere/", ExportMinistere.as_view(), name="export_ministere"),
    path("historique/", HistoriquePage.as_view(), name="historique"),
    path(
        "historique/telecharger/",
        HistoriqueTelecharger.as_view(),
        name="telecharger_historique",
    ),
    path(
        "regles/telecharger/",
        ApprocheDesReglesTelecharger.as_view(),
        name="telecharger_regles",
    ),
    path("ajouter-cts/", CTSCreate.as_view(), name="ajouter_cts"),
    path("modifier-cts/<int:pk>/", CTSUpdate.as_view(), name="modifier_cts"),
    path("synthese-cts/", SyntheseCTS.as_view(), name="synthese_cts"),
    path(
        "ajouter-mutualisation-academique/",
        CreateTempsDeDecharge.as_view(),
        name="ajouter_mutualisation_academique",
    ),
    path(
        "modifier-mutualisation-academique/<int:pk>/",
        UpdateTempsDeDecharge.as_view(),
        name="modifier_mutualisation_academique",
    ),
    path(
        "supprimer-mutualisation-academique/<int:pk>/",
        SuppressionTempsDeDecharge.as_view(),
        name="supprimer_mutualisation_academique",
    ),
    path(
        "ajouter-quota-federation/",
        CreateQuotaETPFederation.as_view(),
        name="ajouter_quota_federation",
    ),
    path(
        "modifier-quota-federation/<int:pk>/",
        UpdateQuotaETPFederation.as_view(),
        name="modifier_quota_federation",
    ),
    path(
        "syndicats-a-relancer/",
        SyndicatsARelancer.as_view(),
        name="syndicats_a_relancer",
    ),
    path(
        "renommer-beneficiaire/",
        RenommerBeneficiaire.as_view(),
        name="renommer_beneficiaire",
    ),
    path(
        "identifier-doublons/",
        IdentifierDoublons.as_view(),
        name="identifier_doublons",
    ),
    path(
        "fusionner-doublons/<int:pk1>/<int:pk2>/",
        FusionnerDoublons.as_view(),
        name="fusionner_doublons",
    ),
]

decharges/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("decharges.decharge.urls", namespace="decharge")),
    path("accounts/", include("decharges.user_manager.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

decharges/user_manager/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import include, path

namespace = "user_manager"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
]

decharges/decharge/models.py
import datetime
import decimal

from django.conf import settings
from django.db import models
from django.forms import ValidationError

from decharges.decharge.validators import (
    code_corps_validator,
    rne_validator,
    validate_first_name,
    validate_last_name,
)


class TempsDeDecharge(models.Model):
    """
    Temps de décharge attribué à un syndicat en début d'année.

    - Ce temps est exprimé en ETP
    - Il est appliqué sur une année donnée (self.annee) et les calculs se basent sur
      l'année dans `parametre.models.ParametresDApplication` pour filtrer
    - Le syndicat donnateur peut être soit la fédération (c'est le défaut),
      soit un autre syndicat (cas spécifique de don de décharge intra-académie)
    """

    syndicat_beneficiaire = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Syndicat bénéficiaire",
        on_delete=models.CASCADE,
        related_name="temps_de_decharges_par_annee",
    )
    annee = models.IntegerField(
        verbose_name="Année à laquelle le temps de décharge est attribué",
        default=2021,
    )
    temps_de_decharge_etp = models.DecimalField(
        verbose_name="Temps de décharge en ETP",
        default=0,
        decimal_places=5,
        max_digits=8,
    )  # précision max: 999.99999
    syndicat_donateur = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Syndicat ayant fait don de temps "
        "(si vide, on considère que cela vient de la fédération)",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="temps_de_decharges_donnes",
    )

    def __str__(self):
        return (
            f"{self.temps_de_decharge_etp} ETP à {self.syndicat_beneficiaire.username} "
            f"en {self.annee}"
        )

    class Meta:
        unique_together = ("annee", "syndicat_donateur", "syndicat_beneficiaire")


class Corps(models.Model):
    code_corps = models.CharField(
        max_length=100,
        unique=True,
        primary_key=True,
        verbose_name="Code corps",
        validators=[code_corps_validator],
    )  # example: 553, 615 etc..
    description = models.CharField(
        verbose_name="Description du Corps",
        max_length=255,
        null=True,
        blank=True,
    )

    def __str__(self):
        if self.description:
            return f"{self.code_corps} ({self.description})"
        return self.code_corps

    class Meta:
        verbose_name = "Corps"
        verbose_name_plural = "Corps"
        ordering = ["code_corps"]


M = "M."
MME = "MME"

choix_civilite = [
    (M, "M."),
    (MME, "MME"),
]

CIVILITE_AFFICHEE = {key: value for key, value in choix_civilite}


class UtilisationTempsDecharge(models.Model):
    """
    Utilisation des temps de décharges par les syndiqués

    - cette utilisation est historisée par année
    - des validations sont appliquées sur les champs, cf **validators.py**
    - cette utilisation de temps de décharge peut être exceptionnellement
      modifiée/ajoutée/supprimée au cours de l'année par la fédération. Les champs
        - `self.supprime_a`
        - `self.cree_a`
        - `self.modifie_a`
        - `self.commentaire_de_mise_a_jour`
      permettront à la fédération d'avoir le maximum d'information sur ces mises à jours
    - L'utilisation de temps de décharge peut soit être une décharge locale, soit une décharge
      fédérale et Solidaires. `self.syndicat` permet de différencier les deux cas
    """

    civilite = models.CharField(
        verbose_name="Civilité",
        max_length=10,
        choices=choix_civilite,
        default=MME,
    )
    prenom = models.CharField(
        max_length=255,
        verbose_name="Prénom en MAJUSCULE",
        validators=[validate_first_name],
        db_index=True,
    )
    nom = models.CharField(
        max_length=255,
        verbose_name="Nom en MAJUSCULE",
        validators=[validate_last_name],
        db_index=True,
    )
    heures_de_decharges = models.DecimalField(
        verbose_name="Temps de décharge utilisées en heures",
        default=0,
        decimal_places=5,
        max_digits=8,
    )  # précision max: 999.99999
    heures_d_obligation_de_service = models.IntegerField(
        verbose_name="Heures d'obligations de service",
        default=0,
    )
    corps = models.ForeignKey(
        Corps,
        verbose_name="Corps",
        on_delete=models.SET_NULL,
        null=True,
    )
    code_etablissement_rne = models.CharField(
        max_length=255,
        verbose_name="Code d'établissement (UAI)",
        validators=[rne_validator],
        db_index=True,
    )

    # meta données
    annee = models.IntegerField(
        verbose_name="Année à laquelle le temps de décharge est utilisé",
        default=2021,
        db_index=True,
    )
    date_debut_decharge = models.DateField(
        verbose_name="Date à laquelle la décharge commence",
        null=True,
        blank=True,
    )
    date_fin_decharge = models.DateField(
        verbose_name="Date à laquelle la décharge se termine",
        null=True,
        blank=True,
    )
    syndicat = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Syndicat qui utilise ce temps",
        on_delete=models.CASCADE,
        related_name="utilisation_temps_de_decharges_par_annee",
    )  # si le syndicat est la fédération, c'est donc une décharge fédérale
    supprime_a = models.DateTimeField(
        verbose_name="La date à laquelle cette décharge a été supprimée",
        null=True,
        blank=True,
    )
    cree_a = models.DateTimeField(
        null=True, blank=True, auto_now_add=True, verbose_name="Date de création"
    )
    modifie_a = models.DateTimeField(
        null=True, blank=True, auto_now=True, verbose_name="Date de mise à jour"
    )
    commentaire_de_mise_a_jour = models.TextField(
        null=True,
        blank=True,
        verbose_name="Historique des modifications",
        help_text="Décrivez factuellement la modification apportée",
    )
    est_une_decharge_solidaires = models.BooleanField(
        default=False,
        verbose_name="Est une décharge solidaires",
        help_text="Cocher cette case uniquement si la décharge "
        "vient d'un autre syndicat que SUD éducation",
    )

    # données importées de l'historique
    etp = models.DecimalField(
        verbose_name="ETP consommé",
        help_text="Ne pas utiliser, présent pour des raisons historiques",
        default=0,
        decimal_places=5,
        max_digits=6,
        blank=True,
    )  # max: 9.99999

    @property
    def etp_utilises(self) -> decimal.Decimal:
        if self.heures_de_decharges != 0 and self.heures_d_obligation_de_service != 0:
            # heures_de_decharges only has 5 decimal places, so we round it up to 5 too
            return round(
                decimal.Decimal(
                    self.heures_de_decharges / self.heures_d_obligation_de_service
                )
                * self.etp_prorata,
                settings.PRECISION_ETP,
            )

        # self.etp peut être renseigné dans le cas où l'objet vient de
        # l'import de l'historique des décharges
        return self.etp

    @property
    def heures_pleines_de_decharges(self) -> int:
        return int(self.heures_de_decharges)

    @property
    def minutes_de_decharges(self) -> int:
        return int(
            round((self.heures_de_decharges - self.heures_pleines_de_decharges) * 60)
        )

    @property
    def etp_prorata(self) -> decimal.Decimal:
        debut_de_lannee = datetime.date(year=self.annee, month=9, day=1)
        fin_de_lannee = datetime.date(year=self.annee + 1, month=8, day=31)
        date_fin_decharge = self.date_fin_decharge or fin_de_lannee
        date_debut_decharge = self.date_debut_decharge or debut_de_lannee
        nb_jours_annee = fin_de_lannee - debut_de_lannee + datetime.timedelta(days=1)
        nb_jours_decharge = (
            date_fin_decharge - date_debut_decharge + datetime.timedelta(days=1)
        )
        return decimal.Decimal(nb_jours_decharge / nb_jours_annee)

    class Meta:
        unique_together = (
            "nom",
            "prenom",
            "annee",
            "code_etablissement_rne",
            "syndicat",
            "est_une_decharge_solidaires",
        )


class UtilisationCreditDeTempsSyndicalPonctuel(models.Model):
    """
    Utilisation des CTS (ou CHS), sur une année donnée, par syndicat
    """

    demi_journees_de_decharges = models.PositiveIntegerField(
        verbose_name="Demi-journées de décharges utilisées",
        default=0,
    )
    annee = models.IntegerField(
        verbose_name="Année à laquelle le temps de décharge est utilisé",
        default=2021,
    )
    syndicat = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name="Syndicat qui utilise ce temps",
        on_delete=models.CASCADE,
        related_name="utilisation_cts_ponctuels_par_annee",
    )

    class Meta:
        unique_together = ("annee", "syndicat")

    @property
    def etp_utilises(self) -> decimal.Decimal:
        nb_days = self.demi_journees_de_decharges / 2
        nb_hours = nb_days * 7
        return round(
            decimal.Decimal(nb_hours / settings.NB_HOURS_IN_A_YEAR),
            settings.PRECISION_ETP,
        )


class TexteAideCreationBeneficiaire(models.Model):
    texte = models.TextField(
        null=True,
        blank=True,
        help_text="Un seul et unique texte doit être créé.",
    )

    def save(self, *args, **kwargs):
        if not self.pk and TexteAideCreationBeneficiaire.objects.exists():
            raise ValidationError("Il ne peut y avoir qu'un seul texte de ce type")
        return super(TexteAideCreationBeneficiaire, self).save(*args, **kwargs)

    def __str__(self):
        return "Texte d'aide à la création d'un bénéficiaire"

decharges/decharge/forms/gestion_doublons_form.py
from django import forms


class IdentifierDoublonsForm(forms.Form):
    doublon_1 = forms.Field(widget=forms.HiddenInput())
    doublon_2 = forms.Field(widget=forms.HiddenInput())

decharges/decharge/views/cts.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView

from decharges import settings
from decharges.decharge.forms import UtilisationCreditDeTempsSyndicalPonctuelForm
from decharges.decharge.mixins import CheckConfigurationMixin, CheckTempsEditableMixin
from decharges.decharge.models import UtilisationCreditDeTempsSyndicalPonctuel
from decharges.decharge.views.utils import calcul_repartition_temps


class CTSCreate(
    CheckConfigurationMixin, LoginRequiredMixin, CheckTempsEditableMixin, CreateView
):
    template_name = "decharge/cts_form.html"
    form_class = UtilisationCreditDeTempsSyndicalPonctuelForm

    def get_success_url(self):
        messages.success(self.request, "CTS enregistré avec succès !")
        return reverse("decharge:index")

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["syndicat"] = self.request.user
        form_kwargs["annee"] = self.params.annee_en_cours
        form_kwargs["federation"] = self.federation
        return form_kwargs


class CTSUpdate(
    CheckConfigurationMixin, LoginRequiredMixin, CheckTempsEditableMixin, UpdateView
):
    template_name = "decharge/cts_form.html"
    form_class = UtilisationCreditDeTempsSyndicalPonctuelForm
    model = UtilisationCreditDeTempsSyndicalPonctuel
    context_object_name = "cts"

    def get_object(self, queryset=None):
        """vérification que l'utilisateur a bien les permissions pour éditer cet objet"""
        cts = super().get_object(queryset=queryset)
        if cts.syndicat != self.request.user and not self.request.user.is_federation:
            raise Http404()
        return cts

    def get_success_url(self):
        messages.success(self.request, "CTS mis à jour avec succès !")
        return reverse("decharge:index")

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["syndicat"] = self.object.syndicat
        form_kwargs["annee"] = self.object.annee
        form_kwargs["federation"] = self.federation
        return form_kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        annee_en_cours = self.params.annee_en_cours
        (
            cts_consommes,
            temps_decharge_federation,
            temps_donnes,
            temps_donnes_total,
            temps_recus_par_des_syndicats,
            temps_recus_par_la_federation,
            temps_restant,
            temps_utilises,
            temps_utilises_total,
        ) = calcul_repartition_temps(annee_en_cours, self.federation, self.request.user)

        total_demi_journees_non_consommees = (
            (temps_restant * settings.NB_HOURS_IN_A_YEAR) / 7 * 2
        )

        context.update(
            {
                "total_etp_non_consommes": round(temps_restant, settings.PRECISION_ETP),
                "total_demi_journees_non_consommees": round(
                    total_demi_journees_non_consommees, settings.PRECISION_ETP
                ),
            }
        )

        return context

decharges/decharge/templates/decharge/page_accueil_syndicat.html
{% extends "decharges/base.html" %}
{% load data_manipulation %}

{% block title %}Accueil{% endblock title %}

{% block maintitle %}Bienvenue !{% endblock maintitle %}
{% block subtitle %}
  Vous visualisez la structure <b>{{ user.username }}</b>{% if user.academie %}, faisant partie de l'académie de {{ user.academie.nom }}{% endif %}
{% endblock %}

{% block content %}
  <section class="container pb-6">
    <div class="card pt-2">
      <header class="card-header">
        <h2 class="card-header-title">Récapitulatif des décharges</h2>
      </header>
      <div class="card-content">
        <ul>
          <li>
            {% if not view_only and request.user.is_federation %}
            <b>Temps total alloué à la fédération&nbsp;:</b>
            {% else %}
            <b>Temps reçu de la fédération&nbsp;:</b>
            {% endif %}
            {{ temps_recus_par_la_federation|floatformat:3 }} ETP
            {% if not view_only %}
              {% if request.user.is_federation %}
                {% if temps_decharge_federation %}
                <a href="{% url 'decharge:modifier_quota_federation' temps_decharge_federation.pk %}" class="button is-info icon"><span class="fa fa-edit"></span></a>
                {% else %}
                <a href="{% url 'decharge:ajouter_quota_federation' %}" class="button is-info icon"><span class="fa fa-edit"></span></a>
                {% endif %}
              {% endif %}
            {% endif %}
          </li>
          <li><b>Temps de décharge consommé&nbsp;:</b> {{ temps_utilises_total|floatformat:3 }} ETP</li>
          <li>
            <b>CTS ponctuel consommé&nbsp;:</b> {% if cts_consommes %}{{ cts_consommes.etp_utilises|floatformat:3 }}{% else %}0{% endif %} ETP
            {% if cts_consommes %}({{ cts_consommes.demi_journees_de_decharges }} demi-journées){% endif %}
            {% if not view_only %}
              {% if decharges_editables or request.user.is_federation %}
                {% if cts_consommes %}
                  <a href="{% url 'decharge:modifier_cts' cts_consommes.pk %}" class="button is-info icon"><span class="fa fa-edit"></span></a>
                {% else %}
                  <a href="{% url 'decharge:ajouter_cts' %}" class="button is-info icon"><span class="fa fa-edit"></span></a>
                {% endif %}
              {% endif %}
            {% endif %}
          </li>
          {% if temps_recus_par_des_syndicats > 0 %}
          <li><b>Temps reçu des syndicats de l'académie&nbsp;:</b> {{ temps_recus_par_des_syndicats|floatformat:3 }} ETP</li>
          {% endif %}
          {% if temps_donnes_total > 0 %}
          <li><b>Temps donné aux syndicats {% if not request.user.is_federation %}de l'académie{% endif %}&nbsp;:</b> {{ temps_donnes_total|floatformat:3 }} ETP</li>
          {% endif %}
        </ul>
        <hr>
        {% if temps_restant > 0 %}
        Il vous reste <strong>{{ temps_restant|floatformat:3 }} ETP</strong> non utilisés
        {% else %}
        <p class="has-text-danger">
          Vous dépassez votre quota de <strong class="has-text-danger">{{ temps_restant|abs|floatformat:3 }} ETP</strong>
        </p>
        {% endif %}
      </div>
    </div>

    <div class="card mt-6">
      <header class="card-header is-align-items-center">
        <h2 class="card-header-title">Bénéficiaires {% if request.user.is_federation %}de décharges fédérales{% endif %}</h2>
        {% if not view_only %}
          {% if decharges_editables or request.user.is_federation %}
          <a class="button is-small is-success mr-2" href="{% url 'decharge:ajouter_beneficiaire' %}">
            <span class="fa fa-sm fa-plus mr-2"></span>Ajout d'un·e bénéficiaire
          </a>
          {% endif %}
        {% endif %}
      </header>
      <div class="card-content">
        <table class="table is-bordered is-striped is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th>Civilité</th>
              <th>Prénom</th>
              <th>Nom</th>
              <th>Temps de décharge</th>
              <th><abbr title="Heures d'obligation de service">ORS</abbr></th>
              <th><abbr title="Code Corps">Corps</abbr></th>
              <th><abbr title="Code établissement">UAI</abbr></th>
              <th>Décharge en ETP</th>
              {% if decharges_editables or request.user.is_federation %}
              <th>Actions</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for temps_utilise in temps_utilises %}
            <tr>
              <td>{{ temps_utilise.civilite }}</td>
              <td>{{ temps_utilise.prenom }}</td>
              <td>{{ temps_utilise.nom }}</td>
              <td>
                {{ temps_utilise.heures_pleines_de_decharges }} h
                {% if temps_utilise.minutes_de_decharges > 0 %}{{ temps_utilise.minutes_de_decharges }}
                {% endif %}
              </td>
              <td>{{ temps_utilise.heures_d_obligation_de_service }}</td>
              <td>{{ temps_utilise.corps.code_corps }}</td>
              <td>{{ temps_utilise.code_etablissement_rne }}</td>
              <td>{{ temps_utilise.etp_utilises|floatformat:3 }} {% if temps_utilise.est_une_decharge_solidaires %}(décharge solidaires){% endif %}</td>
              <td>
              {% if not view_only %}
                {% if decharges_editables or request.user.is_federation %}
                  <a class="button is-info icon" href="{% url 'decharge:modifier_beneficiaire' temps_utilise.pk %}"><span class="fa fa-edit"></span></a>
                  <a class="button is-danger icon" href="{% url 'decharge:supprimer_beneficiaire' temps_utilise.pk %}"><span class="fa fa-trash-alt"></span></a>
                </td>
                {% endif %}
              {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    {% for syndicat, temps_utilises_syndicat in temps_utilises_par_syndicat.items %}
    <div class="card mt-6">
      <header class="card-header is-align-items-center">
        <h2 class="card-header-title">Bénéficiaires du syndicat : {{ syndicat }}</h2>
        {% if not view_only %}
          <a class="button is-small is-success mr-2" href="{% url 'decharge:ajouter_beneficiaire' %}?syndicat={{ syndicat|urlencode }}">
            <span class="fa fa-sm fa-plus mr-2"></span>Ajout d'un·e bénéficiaire
          </a>
        {% endif %}
      </header>
      <div class="card-content">
        <table class="table is-bordered is-striped is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th>Civilité</th>
              <th>Prénom</th>
              <th>Nom</th>
              <th>Temps de décharge</th>
              <th><abbr title="Heures d'obligation de service">ORS</abbr></th>
              <th><abbr title="Code Corps">Corps</abbr></th>
              <th><abbr title="Code établissement">UAI</abbr></th>
              <th>Décharge en ETP</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for temps_utilise in temps_utilises_syndicat %}
            <tr>
              <td>{{ temps_utilise.civilite }}</td>
              <td>{{ temps_utilise.prenom }}</td>
              <td>{{ temps_utilise.nom }}</td>
              <td>
                {{ temps_utilise.heures_pleines_de_decharges }} h
                {% if temps_utilise.minutes_de_decharges > 0 %}
                  {{ temps_utilise.minutes_de_decharges }}
                {% endif %}
              </td>
              <td>{{ temps_utilise.heures_d_obligation_de_service }}</td>
              <td>{{ temps_utilise.corps.code_corps }}</td>
              <td>{{ temps_utilise.code_etablissement_rne }}</td>
              <td>{{ temps_utilise.etp_utilises|floatformat:3 }}</td>
              <td>
                {% if not view_only %}
                  <a class="button is-info icon" href="{% url 'decharge:modifier_beneficiaire' temps_utilise.pk %}"><span class="fa fa-edit"></span></a>
                  <a class="button is-danger icon" href="{% url 'decharge:supprimer_beneficiaire' temps_utilise.pk %}"><span class="fa fa-trash-alt"></span></a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    {% endfor %}

    <div class="card mt-6">
      <header class="card-header is-align-items-center">
        <h2 class="card-header-title">ETP donnés {% if view_only or not request.user.is_federation %}(mutualisation académique){% endif %}</h2>
        {% if not view_only %}
          {% if decharges_editables or request.user.is_federation %}
          <a class="button is-small is-success mr-2" href="{% url 'decharge:ajouter_mutualisation_academique' %}">
            <span class="fa fa-sm fa-plus mr-2"></span>
            {% if request.user.is_federation %}
            Attribuer du temps
            {% else %}
            Partager mon temps
            {% endif %}
          </a>
          {% endif %}
        {% endif %}
      </header>
      <div class="card-content">
        <table class="table is-bordered is-striped is-hoverable is-fullwidth">
          <thead>
            <tr>
              <th>Syndicat bénéficiaire</th>
              <th>ETP donnés</th>
              {% if decharges_editables or request.user.is_federation %}
              <th>Actions</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for temps_donne in temps_donnes %}
            <tr>
              <td>{{ temps_donne.syndicat_beneficiaire.username }}</td>
              <td>{{ temps_donne.temps_de_decharge_etp|floatformat:3 }}</td>
              <td>
              {% if not view_only %}
                {% if decharges_editables or request.user.is_federation %}
                  <a class="button is-primary icon" title="Consulter la saisie du syndicat" href="{% url 'decharge:index-syndicat' temps_donne.syndicat_beneficiaire.pk %}"><span class="fa fa-eye"></span></a>
                  <a class="button is-info icon" href="{% url 'decharge:modifier_mutualisation_academique' temps_donne.pk %}"><span class="fa fa-edit"></span></a>
                  <a class="button is-danger icon" href="{% url 'decharge:supprimer_mutualisation_academique' temps_donne.pk %}"><span class="fa fa-trash-alt"></span></a>
                {% endif %}
              {% endif  %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="card mt-6">
      <header class="card-header is-align-items-center">
        <h2 class="card-header-title">Besoin d'aide ?</h2>
      </header>
      <div class="card-content">
        <p>
          Pour toute question, n'hésitez pas nous envoyer un mail à <a href="mailto:decharges@sudeducation.org">decharges@sudeducation.org</a>. On se fera un plaisir de vous répondre !
        </p>
      </div>
    </div>
  </section>
{% endblock content %}