decharges/decharge/urls.py
from django.urls import path

from decharges.decharge.views import (
    ApprocheDesReglesTelecharger,
    CreateQuotaETPFederation,
    CreateTempsDeDecharge,
    CreateUtilisationTempsDecharge,
    CTSCreate,
    CTSUpdate,
    ExportMinistere,
    FusionnerDoublons,
    HistoriquePage,
    HistoriqueTelecharger,
    IdentifierDoublons,
    ImportTempsSyndicats,
    PageAccueilSyndicatView,
    RenommerBeneficiaire,
    SuppressionTempsDeDecharge,
    SuppressionUtilisationTempsDecharge,
    SyndicatsARelancer,
    SyntheseCTS,
    UpdateQuotaETPFederation,
    UpdateTempsDeDecharge,
    UpdateUtilisationTempsDecharge,
)
from decharges.decharge.views.accueil import PageAccueilSyndicatChoisiView

app_name = "decharge"

urlpatterns = [
    path("", PageAccueilSyndicatView.as_view(), name="index"),
    path(
        "consulter-saisie/<int:pk>/",
        PageAccueilSyndicatChoisiView.as_view(),
        name="index-syndicat",
    ),
    path("import/", ImportTempsSyndicats.as_view(), name="import_temps"),
    path(
        "ajouter-beneficiaire/",
        CreateUtilisationTempsDecharge.as_view(),
        name="ajouter_beneficiaire",
    ),
    path(
        "modifier-beneficiaire/<int:pk>/",
        UpdateUtilisationTempsDecharge.as_view(),
        name="modifier_beneficiaire",
    ),
    path(
        "supprimer-beneficiaire/<int:pk>/",
        SuppressionUtilisationTempsDecharge.as_view(),
        name="supprimer_beneficiaire",
    ),
    path("export-ministere/", ExportMinistere.as_view(), name="export_ministere"),
    path("historique/", HistoriquePage.as_view(), name="historique"),
    path(
        "historique/telecharger/",
        HistoriqueTelecharger.as_view(),
        name="telecharger_historique",
    ),
    path(
        "regles/telecharger/",
        ApprocheDesReglesTelecharger.as_view(),
        name="telecharger_regles",
    ),
    path("ajouter-cts/", CTSCreate.as_view(), name="ajouter_cts"),
    path("modifier-cts/<int:pk>/", CTSUpdate.as_view(), name="modifier_cts"),
    path("synthese-cts/", SyntheseCTS.as_view(), name="synthese_cts"),
    path(
        "ajouter-mutualisation-academique/",
        CreateTempsDeDecharge.as_view(),
        name="ajouter_mutualisation_academique",
    ),
    path(
        "modifier-mutualisation-academique/<int:pk>/",
        UpdateTempsDeDecharge.as_view(),
        name="modifier_mutualisation_academique",
    ),
    path(
        "supprimer-mutualisation-academique/<int:pk>/",
        SuppressionTempsDeDecharge.as_view(),
        name="supprimer_mutualisation_academique",
    ),
    path(
        "ajouter-quota-federation/",
        CreateQuotaETPFederation.as_view(),
        name="ajouter_quota_federation",
    ),
    path(
        "modifier-quota-federation/<int:pk>/",
        UpdateQuotaETPFederation.as_view(),
        name="modifier_quota_federation",
    ),
    path(
        "syndicats-a-relancer/",
        SyndicatsARelancer.as_view(),
        name="syndicats_a_relancer",
    ),
    path(
        "renommer-beneficiaire/",
        RenommerBeneficiaire.as_view(),
        name="renommer_beneficiaire",
    ),
    path(
        "identifier-doublons/",
        IdentifierDoublons.as_view(),
        name="identifier_doublons",
    ),
    path(
        "fusionner-doublons/<int:pk1>/<int:pk2>/",
        FusionnerDoublons.as_view(),
        name="fusionner_doublons",
    ),
]

decharges/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("decharges.decharge.urls", namespace="decharge")),
    path("accounts/", include("decharges.user_manager.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

decharges/user_manager/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import include, path

namespace = "user_manager"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
]

decharges/decharge/forms/gestion_doublons_form.py
from django import forms


class IdentifierDoublonsForm(forms.Form):
    doublon_1 = forms.Field(widget=forms.HiddenInput())
    doublon_2 = forms.Field(widget=forms.HiddenInput())

decharges/decharge/views/accueil.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView

from decharges.decharge.mixins import CheckConfigurationMixin, FederationRequiredMixin
from decharges.decharge.models import UtilisationTempsDecharge
from decharges.decharge.views.utils import calcul_repartition_temps
from decharges.user_manager.models import Syndicat


class PageAccueilSyndicatView(
    CheckConfigurationMixin, LoginRequiredMixin, TemplateView
):
    template_name = "decharge/page_accueil_syndicat.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        annee_en_cours = self.params.annee_en_cours
        (
            cts_consommes,
            temps_decharge_federation,
            temps_donnes,
            temps_donnes_total,
            temps_recus_par_des_syndicats,
            temps_recus_par_la_federation,
            temps_restant,
            temps_utilises,
            temps_utilises_total,
        ) = calcul_repartition_temps(annee_en_cours, self.federation, self.request.user)

        if self.request.user.is_federation and not self.params.decharges_editables:
            # Si on est en cours d'année, la fédé peut éditer les décharges des syndicats
            temps_utilises_par_syndicat = {}
            for temps_utilise in UtilisationTempsDecharge.objects.filter(
                annee=annee_en_cours,
                supprime_a__isnull=True,
            ).exclude(syndicat=self.federation):
                temps_utilises_par_syndicat[
                    temps_utilise.syndicat.username
                ] = temps_utilises_par_syndicat.get(
                    temps_utilise.syndicat.username, []
                ) + [
                    temps_utilise
                ]
            context["temps_utilises_par_syndicat"] = temps_utilises_par_syndicat

        context.update(
            {
                "temps_decharge_federation": temps_decharge_federation,
                "temps_restant": round(temps_restant, settings.PRECISION_ETP),
                "cts_consommes": cts_consommes,
                "temps_donnes": temps_donnes,
                "temps_utilises": temps_utilises,
                "temps_recus_par_la_federation": round(
                    temps_recus_par_la_federation, settings.PRECISION_ETP
                ),
                "temps_recus_par_des_syndicats": round(
                    temps_recus_par_des_syndicats, settings.PRECISION_ETP
                ),
                "temps_utilises_total": round(
                    temps_utilises_total, settings.PRECISION_ETP
                ),
                "temps_donnes_total": round(temps_donnes_total, settings.PRECISION_ETP),
                "decharges_editables": self.params.decharges_editables,
            }
        )

        return context


class PageAccueilSyndicatChoisiView(
    CheckConfigurationMixin, FederationRequiredMixin, TemplateView
):
    template_name = "decharge/page_accueil_syndicat.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        syndicat_choisi = get_object_or_404(Syndicat, pk=self.kwargs["pk"])
        annee_en_cours = self.params.annee_en_cours
        (
            cts_consommes,
            temps_decharge_federation,
            temps_donnes,
            temps_donnes_total,
            temps_recus_par_des_syndicats,
            temps_recus_par_la_federation,
            temps_restant,
            temps_utilises,
            temps_utilises_total,
        ) = calcul_repartition_temps(annee_en_cours, self.federation, syndicat_choisi)

        if self.request.user.is_federation and not self.params.decharges_editables:
            # Si on est en cours d'année, la fédé peut éditer les décharges des syndicats
            temps_utilises_par_syndicat = {}
            for temps_utilise in UtilisationTempsDecharge.objects.filter(
                annee=annee_en_cours,
                supprime_a__isnull=True,
            ).exclude(syndicat=self.federation):
                temps_utilises_par_syndicat[
                    temps_utilise.syndicat.username
                ] = temps_utilises_par_syndicat.get(
                    temps_utilise.syndicat.username, []
                ) + [
                    temps_utilise
                ]
            context["temps_utilises_par_syndicat"] = temps_utilises_par_syndicat

        context.update(
            {
                "temps_decharge_federation": temps_decharge_federation,
                "temps_restant": round(temps_restant, settings.PRECISION_ETP),
                "cts_consommes": cts_consommes,
                "temps_donnes": temps_donnes,
                "temps_utilises": temps_utilises,
                "temps_recus_par_la_federation": round(
                    temps_recus_par_la_federation, settings.PRECISION_ETP
                ),
                "temps_recus_par_des_syndicats": round(
                    temps_recus_par_des_syndicats, settings.PRECISION_ETP
                ),
                "temps_utilises_total": round(
                    temps_utilises_total, settings.PRECISION_ETP
                ),
                "temps_donnes_total": round(temps_donnes_total, settings.PRECISION_ETP),
                "decharges_editables": self.params.decharges_editables,
                "user": syndicat_choisi,
            }
        )

        context["view_only"] = True

        return context

decharges/decharge/views/cts.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView

from decharges import settings
from decharges.decharge.forms import UtilisationCreditDeTempsSyndicalPonctuelForm
from decharges.decharge.mixins import CheckConfigurationMixin, CheckTempsEditableMixin
from decharges.decharge.models import UtilisationCreditDeTempsSyndicalPonctuel
from decharges.decharge.views.utils import calcul_repartition_temps


class CTSCreate(
    CheckConfigurationMixin, LoginRequiredMixin, CheckTempsEditableMixin, CreateView
):
    template_name = "decharge/cts_form.html"
    form_class = UtilisationCreditDeTempsSyndicalPonctuelForm

    def get_success_url(self):
        messages.success(self.request, "CTS enregistré avec succès !")
        return reverse("decharge:index")

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["syndicat"] = self.request.user
        form_kwargs["annee"] = self.params.annee_en_cours
        form_kwargs["federation"] = self.federation
        return form_kwargs


class CTSUpdate(
    CheckConfigurationMixin, LoginRequiredMixin, CheckTempsEditableMixin, UpdateView
):
    template_name = "decharge/cts_form.html"
    form_class = UtilisationCreditDeTempsSyndicalPonctuelForm
    model = UtilisationCreditDeTempsSyndicalPonctuel
    context_object_name = "cts"

    def get_object(self, queryset=None):
        """vérification que l'utilisateur a bien les permissions pour éditer cet objet"""
        cts = super().get_object(queryset=queryset)
        if cts.syndicat != self.request.user and not self.request.user.is_federation:
            raise Http404()
        return cts

    def get_success_url(self):
        messages.success(self.request, "CTS mis à jour avec succès !")
        return reverse("decharge:index")

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["syndicat"] = self.object.syndicat
        form_kwargs["annee"] = self.object.annee
        form_kwargs["federation"] = self.federation
        return form_kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        annee_en_cours = self.params.annee_en_cours
        (
            cts_consommes,
            temps_decharge_federation,
            temps_donnes,
            temps_donnes_total,
            temps_recus_par_des_syndicats,
            temps_recus_par_la_federation,
            temps_restant,
            temps_utilises,
            temps_utilises_total,
        ) = calcul_repartition_temps(annee_en_cours, self.federation, self.request.user)

        total_demi_journees_non_consommees = (
            (temps_restant * settings.NB_HOURS_IN_A_YEAR) / 7 * 2
        )

        context.update(
            {
                "total_etp_non_consommes": round(temps_restant, settings.PRECISION_ETP),
                "total_demi_journees_non_consommees": round(
                    total_demi_journees_non_consommees, settings.PRECISION_ETP
                ),
            }
        )

        return context

decharges/decharge/views/export_ministere.py
from datetime import date

import pandas
from django.http import HttpResponse
from django.views.generic.base import View

from decharges.decharge.mixins import CheckConfigurationMixin, FederationRequiredMixin
from decharges.decharge.models import UtilisationTempsDecharge
from decharges.decharge.views.utils import aggregation_par_beneficiaire


def get_data_frame_ministere(utilisations_temps_decharges):
    columns = aggregation_par_beneficiaire(utilisations_temps_decharges)

    return pandas.DataFrame(
        {
            "Code organisation": pandas.Series(
                columns["code_organisations"], dtype="string"
            ),
            "Code civilité": pandas.Series(columns["m_mmes"], dtype="string"),
            "Prénom": pandas.Series(columns["prenoms"], dtype="string"),
            "Nom": pandas.Series(columns["noms"], dtype="string"),
            "Heures de décharge": pandas.Series(
                columns["heures_decharges"], dtype="int"
            ),
            "Minutes de décharge": pandas.Series(
                columns["minutes_decharges"], dtype="int"
            ),
            "Heures d'obligations de service": pandas.Series(
                columns["heures_ors"], dtype="int"
            ),
            "Aire": pandas.Series(columns["aires"], dtype="int"),
            "Corps": pandas.Series(columns["corps"], dtype="string"),
            "Etablissement": pandas.Series(columns["rnes"], dtype="string"),
            "Date d'effet": pandas.Series(columns["dates_debut"], dtype="string"),
            "Date de fin": pandas.Series(columns["dates_fin"], dtype="string"),
        }
    )


class ExportMinistere(CheckConfigurationMixin, FederationRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        annee = self.params.annee_en_cours

        data_frame = get_data_frame_ministere(
            UtilisationTempsDecharge.objects.filter(
                annee=annee,
                supprime_a__isnull=True,
                est_une_decharge_solidaires=False,
            )
            .prefetch_related("corps")
            .order_by("nom", "prenom")
        )
        response = HttpResponse("", content_type="application/force-download")
        data_frame.to_csv(response, index=False)
        today = date.today()
        response["Content-Disposition"] = (
            "attachment; filename=SUD éducation - déclaration initiale "
            f"{annee}-{annee+1} - {today}.csv"
        )
        return response

decharges/decharge/views/import_temps_syndicats.py
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse
from django.views.generic import FormView

from decharges.decharge.forms import ImportTempsSyndicatsForm
from decharges.decharge.mixins import CheckConfigurationMixin, FederationRequiredMixin
from decharges.decharge.models import TempsDeDecharge


class ImportTempsSyndicats(CheckConfigurationMixin, FederationRequiredMixin, FormView):
    template_name = "decharge/import_temps_syndicats.html"
    form_class = ImportTempsSyndicatsForm

    def get_success_url(self):
        return reverse("decharge:index")

    def form_valid(self, form):
        federation = self.request.user
        updated = 0
        created = 0
        for syndicat, etp in form.cleaned_data["temps_de_decharge"]:
            temps_de_decharge_existant = TempsDeDecharge.objects.filter(
                Q(syndicat_donateur__isnull=True) | Q(syndicat_donateur=federation),
                annee=form.cleaned_data["annee"],
                syndicat_beneficiaire=syndicat,
            )
            if temps_de_decharge_existant:
                temps_de_decharge_existant.update(temps_de_decharge_etp=etp)
                updated += 1
            else:
                TempsDeDecharge.objects.create(
                    syndicat_donateur=federation,
                    annee=form.cleaned_data["annee"],
                    syndicat_beneficiaire=syndicat,
                    temps_de_decharge_etp=etp,
                )
                created += 1

        message = "Import terminé avec succès."
        if created > 0:
            message += f" {created} temps créés."
        if updated > 0:
            message += f" {updated} temps mis à jour."
        messages.success(self.request, message)

        return super().form_valid(form)

decharges/templates/decharges/base.html
{% load static bulma_tags %}

<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock title %} | SUD éducation</title>
  <link rel="shortcut icon" href="{% static 'img/icon.jpg' %}">
  {% block css %}
    <link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link href="{% static 'fontawesome/css/all.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock extra_css %}
  {% endblock css %}
</head>
<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item logo" href="/">
        <img src="{% static 'img/logoSUD2.svg' %}" width="112" height="28" alt="">
      </a>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarRef">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarRef" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="/">
          Accueil
        </a>

        {% if request.user.is_federation %}
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Administration
          </a>

          <div class="navbar-dropdown">
            <a class="navbar-item" href="{% url 'decharge:import_temps' %}">
              Import des temps
            </a>
            <a class="navbar-item" href="{% url 'decharge:historique' %}">
              Historique
            </a>
            <a class="navbar-item" href="{% url 'decharge:export_ministere' %}">
              Export ministère
            </a>
            <a class="navbar-item" href="{% url 'decharge:syndicats_a_relancer' %}">
              Syndicats à relancer
            </a>
            <a class="navbar-item" href="{% url 'decharge:synthese_cts' %}">
              Synthèse et CTS utilisés
            </a>
            <a class="navbar-item" href="{% url 'decharge:renommer_beneficiaire' %}">
              Renommer/muter un·e bénéficiaire
            </a>
            <a class="navbar-item" href="{% url 'decharge:identifier_doublons' %}">
              Identifier les doublons
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item" href="{% url 'admin:parametre_parametresdapplication_changelist' %}">
              Configuration
            </a>
          </div>
        </div>
        {% endif %}
        <a class="navbar-item" href="mailto:decharges@sudeducation.org">
          Besoin d'aide ?
        </a>
      </div>


      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if request.user.is_anonymous %}
            <a class="button is-light" href="{% url 'login' %}">
              Connexion
            </a>
            {% else %}
            <b class="navbar-item">{{ user.username }}</b>
            <a class="button is-light" href="{% url 'logout' %}">
              Déconnexion
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

  {% block messages %}
    {% if messages %}
      <div class="container mt-4">
        <div class="messages columns is-desktop">
          <div class="column">
            {% for message in messages %}
              <div class="notification {% if message.tags %}is-{{ message.tags|bulma_message_tag }}{% endif %}">
                <button class="delete remove-notification" aria-label="delete"></button>
                {{ message }}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endif %}
  {% endblock messages %}

  <section class="hero is-sud">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          {% block maintitle %}{% endblock maintitle %}
        </h1>
        <p class="subtitle">
          {% block subtitle %}{% endblock subtitle %}
        </p>
      </div>
  </section>

  <div class="container">
  {% block content %}{% endblock content %}
  </div>

{% block javascript %}
  <script type="application/javascript" src="{% static 'js/app.js' %}"></script>
  {% block extra_javascript %}{% endblock extra_javascript %}
{% endblock javascript %}
</body>
</html>